#!/bin/sh

write_map()
{
    slicename=${1}
    fileglob=${2}
    printf "package backend\n\n"
    printf "var ${slicename} = map[string][]byte{\n"
    for filepath in ${fileglob}; do
        slice=$(basename "${filepath%%.*}")
        printf "\t\"${slice}\": {\n"
        bytes=$(gohex -c 12 -i 2 -s "${filepath}")
        printf "${bytes}\n"
        printf "\t},\n"
    done
    printf "}\n"
}

go get github.com/wamuir/gohex
write_map "schema" "schema/*.sql" > "schema.go"
write_map "statements" "statements/*.sql" > "statements.go"
